"""initial migration

Revision ID: b3aa2e77c914
Revises: 
Create Date: 2026-06-27 16:58:17.456295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3aa2e77c914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('subdomain', sa.String(length=60), nullable=False),
    sa.Column('plan', sa.Enum('STARTER', 'PROFESSIONAL', 'CLINIC', 'ENTERPRISE', name='clinic_plan'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVA', 'SUSPENDIDA', 'CANCELADA', 'PRUEBA', name='clinic_status'), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('subdomain')
    )
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.create_index('ix_clinics_slug', ['slug'], unique=True)
        batch_op.create_index('ix_clinics_status', ['status'], unique=False)
        batch_op.create_index('ix_clinics_subdomain', ['subdomain'], unique=True)

    op.create_table('subscriptions',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('STARTER', 'PROFESSIONAL', 'CLINIC', 'ENTERPRISE', name='subscription_plan'), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MENSUAL', 'TRIMESTRAL', 'ANUAL', name='billing_cycle'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVA', 'PRUEBA', 'PENDIENTE_PAGO', 'SUSPENDIDA', 'CANCELADA', 'VENCIDA', name='subscription_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method_id', sa.String(length=200), nullable=True),
    sa.Column('price_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscriptions_clinic', ['clinic_id'], unique=False)
        batch_op.create_index('ix_subscriptions_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MEDICO', 'RECEPCIONISTA', 'PACIENTE', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('doctors',
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_license_number'), ['license_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_specialty'), ['specialty'], unique=False)

    op.create_table('invoices',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('BORRADOR', 'EMITIDA', 'PAGADA', 'VENCIDA', 'CANCELADA', name='invoice_status'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_clinic', ['clinic_id'], unique=False)
        batch_op.create_index('ix_invoices_number', ['number'], unique=True)
        batch_op.create_index('ix_invoices_status', ['status'], unique=False)
        batch_op.create_index('ix_invoices_subscription', ['subscription_id'], unique=False)

    op.create_table('patients',
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MASCULINO', 'FEMENINO', 'OTRO', 'NO_ESPECIFICADO', name='gender'), nullable=False),
    sa.Column('blood_type', sa.Enum('O_POS', 'O_NEG', 'A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'DESCONOCIDO', name='blood_type'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('allergies', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patients_clinic', ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_document_number'), ['document_number'], unique=False)

    op.create_table('appointments',
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('receptionist_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'CONFIRMADA', 'EN_CONSULTA', 'COMPLETADA', 'CANCELADA', name='appointment_status'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receptionist_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointments_clinic', ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index('ix_appointments_doctor_start', ['doctor_id', 'start_time'], unique=False)
        batch_op.create_index('ix_appointments_patient_start', ['patient_id', 'start_time'], unique=False)
        batch_op.create_index('ix_appointments_status', ['status'], unique=False)

    op.create_table('doctor_schedules',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='weekday'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'weekday', name='uq_doctor_schedule_doctor_weekday')
    )
    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_doctor_schedule_doctor', ['doctor_id'], unique=False)

    op.create_table('payments',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('method', sa.Enum('STRIPE', 'CONEKTA', 'MERCADO_PAGO', 'TRANSFERENCIA', 'EFECTIVO', 'MANUAL', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'COMPLETADO', 'FALLIDO', 'REEMBOLSADO', name='payment_status'), nullable=False),
    sa.Column('transaction_id', sa.String(length=200), nullable=True),
    sa.Column('gateway_response', sa.String(length=2000), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_invoice', ['invoice_id'], unique=False)
        batch_op.create_index('ix_payments_status', ['status'], unique=False)
        batch_op.create_index('ix_payments_transaction', ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('medical_records',
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('blood_pressure', sa.String(length=20), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index('ix_medical_records_clinic', ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index('ix_medical_records_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('ix_medical_records_patient', ['patient_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('medications', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index('ix_prescriptions_clinic', ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index('ix_prescriptions_code', ['code'], unique=True)
        batch_op.create_index('ix_prescriptions_doctor', ['doctor_id'], unique=False)
        batch_op.create_index('ix_prescriptions_patient', ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_prescriptions_patient')
        batch_op.drop_index('ix_prescriptions_doctor')
        batch_op.drop_index('ix_prescriptions_code')
        batch_op.drop_index(batch_op.f('ix_prescriptions_clinic_id'))
        batch_op.drop_index('ix_prescriptions_clinic')

    op.drop_table('prescriptions')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index('ix_medical_records_patient')
        batch_op.drop_index('ix_medical_records_doctor')
        batch_op.drop_index(batch_op.f('ix_medical_records_clinic_id'))
        batch_op.drop_index('ix_medical_records_clinic')

    op.drop_table('medical_records')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_transaction_id'))
        batch_op.drop_index('ix_payments_transaction')
        batch_op.drop_index('ix_payments_status')
        batch_op.drop_index('ix_payments_invoice')

    op.drop_table('payments')
    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_doctor_schedule_doctor')

    op.drop_table('doctor_schedules')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_status')
        batch_op.drop_index('ix_appointments_patient_start')
        batch_op.drop_index('ix_appointments_doctor_start')
        batch_op.drop_index(batch_op.f('ix_appointments_clinic_id'))
        batch_op.drop_index('ix_appointments_clinic')

    op.drop_table('appointments')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_document_number'))
        batch_op.drop_index(batch_op.f('ix_patients_clinic_id'))
        batch_op.drop_index('ix_patients_clinic')

    op.drop_table('patients')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_subscription')
        batch_op.drop_index('ix_invoices_status')
        batch_op.drop_index('ix_invoices_number')
        batch_op.drop_index('ix_invoices_clinic')

    op.drop_table('invoices')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_specialty'))
        batch_op.drop_index(batch_op.f('ix_doctors_license_number'))
        batch_op.drop_index(batch_op.f('ix_doctors_clinic_id'))

    op.drop_table('doctors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_clinic_id'))

    op.drop_table('users')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_status')
        batch_op.drop_index('ix_subscriptions_clinic')

    op.drop_table('subscriptions')
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index('ix_clinics_subdomain')
        batch_op.drop_index('ix_clinics_status')
        batch_op.drop_index('ix_clinics_slug')

    op.drop_table('clinics')
    # ### end Alembic commands ###
