"""add stripe fields

Revision ID: bbeb85bb1399
Revises: b3aa2e77c914
Create Date: 2026-06-28 12:50:17.142207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbeb85bb1399'
down_revision = 'b3aa2e77c914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_clinics_stripe_customer_id'), ['stripe_customer_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_subscription_id'))
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_subscription_id')

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_stripe_customer_id'))
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
